### ISSUE TITLE
Build 'share this message' component

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#1]
Each choice page will have a shareable pre-made message specific to the page.

## It would be shareable to:
- [x] Twitter
- [x] Facebook
- [x] Whatsapp
- [x] LinkedIn
- [x] Email

This component will be the same on all choice pages but there are 3 places where the descriptive text is custom to the page, and each of the share messages will be custom.

It would be great if we could set up one component for this that works across all choice pages, with one place to input the unique content for each one.

![image](https://user-images.githubusercontent.com/310547/56863020-61a76900-69b1-11e9-8979-abf85ca8e302.png)

**Comment by rachelfranklin1** [comment]
I'd like to take this one @shylands.  I've not used SASS before, so it will be a nice easy one for me to get started with.

**Comment by shylands** [comment]
@rachelfranklin1 Great sounds good! Any questions let me know. Thanks for your help.

**Comment by rachelfranklin1** [comment]
hey @shylands can you send me the whatsapp icon you are using please?

**Comment by shylands** [comment]
@rachelfranklin1 Yeah here they all are, includes the new Facebook icon.




[icons.zip](https://github.com/shylands/climatechoice/files/3137401/icons.zip)

**Comment by shylands** [comment]
@rachelfranklin1 Hey had another thought here to add in a copy link button, which copies the current page URL to clipboard when pressed. Maybe just a bubble that appears over the screen that says copied to clipboard like the attached example, but any obvious visual feedback would do. Thanks!

![image](https://user-images.githubusercontent.com/310547/57207350-52d23f00-6fcd-11e9-89da-d7aa3484c695.png)
 
![climatechoice-site sketch 2019-05-06 07-03-37](https://user-images.githubusercontent.com/310547/57207326-1999cf00-6fcd-11e9-9ffa-ddb5e753eb5d.png)

[link-icon.svg.zip](https://github.com/shylands/climatechoice/files/3146544/link-icon.svg.zip)

**Comment by shylands** [comment]
Hey @rachelfranklin1 I've been writing content for these and was wondering a couple of things about the FB message.

1. The implementation used a Facebook quote, is there any reason we should be doing this other than a message? I just think if the message bit is already pre-filled instead the user is more likely to share as some might not want to think of a message to write (or know they don't have to write one).
2. Is it possible to have multiple FB hashtags? No big deal if not.

Thanks!
