### ISSUE TITLE
Button name elements are currently rendering a small blank button

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#122]
`<button name="">` tags are for jump links to specific page sections. They should be invisible but the current implementation renders small blank buttons like this:

![Change how you eat to help prevent climate change | ClimateChoice 2019-06-25 20-03-26](https://user-images.githubusercontent.com/310547/60121864-52ac1f80-9784-11e9-86cb-ad169bfac581.png)

We need to render these invisible while maintaining the functionality.

**Comment by shakti97** [comment]
is this issue still incomplete or done  but not marked closed?

**Comment by shylands** [comment]
@shakti97 Hey this is still happening on the TLDR banners for example https://climatechoice.co/change-how-you-travel#tldr

**Comment by bkstephen** [comment]
Can I give this a try if it's not taken, please? It might take a couple of days

**Comment by shakti97** [comment]
Can I give it a give it try ?

**Comment by shylands** [comment]
Hey @shakti97 you asked first so feel free!

**Comment by bkstephen** [comment]
@shylands That is actually perfect because I found a content page write up  I'd like to help to make instead. https://github.com/impactmakers/climatechoice/issues/106
