### ISSUE TITLE
Add link to 'idea to save energy at home' article to /use-less-energy

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#149]
https://finalscope.com/award-winning-ideas-to-save-energy-at-home/

**Comment by philsturgeon** [comment]
A great guide on this is [Shrink that Footprint](http://shrinkthatfootprint.com/the-beginners-guide-to-lower-heating-bills), a site which could be considered a forebear of climate choice but no longer maintained.

We could talk about smart meters a bit (that which is tracked can be changed or whatever the quote is):

- https://sense.com/
- https://getbarry.co/

Maybe also mention passive homes just super briefly and link off to them, but that is potentially a bit advanced.

**Comment by philsturgeon** [comment]
Oh and other ideas for home improvements over here https://protect.earth/home-improvements/

**Comment by vibalijoshi** [comment]
Hi collaborators, I am interested to do fix this, can you properly tell what needs to be fixed? I am a bit confused
Cheers
