### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#19]
There's an issue with the Netlify build from Master. It seems to be trying to build a path called /test/ which doesn't exist.

11:49:34 AM: error Building static HTML failed for path "/test/"
11:49:34 AM: See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html
11:49:34 AM:   24 |             type="hidden"
11:49:34 AM:   25 |             id="hidden-input"
11:49:34 AM: > 26 |             value={document.location.href}
11:49:34 AM:      |                    ^
11:49:34 AM:   27 |           />
11:49:34 AM:   28 |           <div className={styles.logo}>
11:49:34 AM:   29 |             <TwitterIcon fillColor="#76a9ea" />
11:49:34 AM: 
11:49:34 AM:   WebpackError: ReferenceError: document is not defined
11:49:34 AM:   
11:49:34 AM:   - TwitterButton.js:26 TwitterButton
11:49:34 AM:     lib/src/components/SocialButtons/TwitterButton.js:26:20
11:49:34 AM:   
11:49:34 AM:   - bootstrap:22 c
11:49:34 AM:     lib/webpack/bootstrap:22:1
11:49:34 AM:   
11:49:34 AM:   - bootstrap:25 Sa
11:49:34 AM:     lib/webpack/bootstrap:25:1
11:49:34 AM:   
11:49:34 AM:   - bootstrap:30 a.render
11:49:34 AM:     lib/webpack/bootstrap:30:1
11:49:34 AM:   
11:49:34 AM:   - bootstrap:30 a.read
11:49:35 AM: failed during stage 'building site': Build script returned non-zero exit code: 1

**Comment by shylands** [comment]
@ThePaulMcBride Yo man, I am completely stumped by this one, do you have any ideas what could be causing it?

**Comment by ThePaulMcBride** [comment]
The `document is not defined` part looks like it is probably responsible. I'll take a look at lunch time!

**Comment by ThePaulMcBride** [comment]
Yep, I just had a quick look there, it's definitely that we are trying to reference `document.location` in several places. That works for client rendered pages, but at build time, on the server, document doesn't exist. We need a more robust way of getting the url for the current page.

Gatsby uses Reach Router under the hood and I think it will be able to give us the url. I'll have a play later!

**Comment by shylands** [comment]
Awesome thanks!

**Comment by ThePaulMcBride** [comment]
This seems to be working now. I'd be keen for @rachelfranklin1 to take a look at the sharing buttons to make sure I didn't do anything stupid!

**Comment by shylands** [comment]
Awesome tested all of the social media and seem to be working fine for me!

Best,
Steven
