### ISSUE TITLE
Setup choice pages

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#2]
## The choice pages are:
/change-how-you-eat
/change-how-you-travel
/choose-renewable-energy
/use-less-energy
/change-your-lifestyle

## Build Approach
I'm not 100% sure what the best way to set these up is. They will all follow a similar structure with different content, but there may be some differences that change the structure or have less content on specific choice pages.

![choice-eat](https://user-images.githubusercontent.com/310547/57236755-0bc46800-7026-11e9-97b3-c967ed4461af.jpg)
![choice-less-energy](https://user-images.githubusercontent.com/310547/57236756-0bc46800-7026-11e9-9b18-a50e10ea4cc3.jpg)
![choice-lifestyle](https://user-images.githubusercontent.com/310547/57236757-0bc46800-7026-11e9-961e-709a12b8e23e.jpg)
![choice-renewables](https://user-images.githubusercontent.com/310547/57236758-0bc46800-7026-11e9-8773-a1ca3936dea2.jpg)
![choice-travel](https://user-images.githubusercontent.com/310547/57236759-0c5cfe80-7026-11e9-82f7-6fd87b9b44e0.jpg)

**Comment by shylands** [comment]
@ThePaulMcBride hey could I get your dev opinion on this. I've roughly mocked up the content for the choice pages. Do you think is it worthwhile trying to set this up in a reusable way or should I just rattle on and build them statically? They are fairly similar now but I get the feeling they will become more unique with time so might be wasted effort? Cheers!

**Comment by ThePaulMcBride** [comment]
All of these pages are different, but them seem to be made up by the same kind of modules over and over again. Getting it all working with a CMS wouldn't be any fun, but it might be with looking into [mdx](https://gatsby-mdx.netlify.com/).

You'd write the content in markdown but be able to embed React components with in the markdown.

**Comment by shylands** [comment]
@ThePaulMcBride Cheers look useful! I'd probably spend too much time trying to work out how to get it functional so I might just batter ahead without for now
