### ISSUE TITLE
Implement rotating Climate Change effects in homeIntro banner component

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#22]
It would be cool if the orange 'mass extinctions text' rotated through various effects every couple of seconds to try and emphasise how much of the world is going to be affected. Options could be:

- [ ] mass extinctions
- [ ] extreme weather
- [ ] water shortages
- [ ] crop failures
- [ ] wildfires
- [ ] mass migrations
- [ ] sea level rises

![image](https://user-images.githubusercontent.com/310547/57550438-a98d9f00-7366-11e9-9f16-dc0c42183a81.png)

**Comment by shylands** [comment]
@rachelfranklin1 @ThePaulMcBride @mattbudde another one here if anyone fancies it!

**Comment by ThePaulMcBride** [comment]
This sounds like fun! I'll do it 💯

**Comment by rachelfranklin1** [comment]
unreal, excited to see this live 😻

**Comment by ThePaulMcBride** [comment]
This is now live, though it might need a few styling tweaks on mobile

**Comment by shylands** [comment]
Ah looks great! Is it possible to make the delay between changing another second? And maybe speed up the time it takes to type in/out?

**Comment by ThePaulMcBride** [comment]
Just updated there now 👍
