### ISSUE TITLE
Implement read status message on ChoiceGrid

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#26]
From Paul:

> There are a few ways we could do this. The simplest was is probably using the CSS visited psudo-class, though it might not be suitable if the html doesn't quite match up to what we'd need.
> 
> Otherwise, we could store the information of what pages you've viewed in local storage or something. Is this already built? If so, I can have a stab at hooking it up.

**Comment by shylands** [comment]
@ThePaulMcBride the homepage grid is setup now if you still fancy this one

**Comment by ThePaulMcBride** [comment]
Yea, I'll take a look at this later today!

**Comment by ThePaulMcBride** [comment]
Alright, turns out you can only change certain styles using the `visited` pseudo classes and it won't work for what we need. I'll need to build it with a local storage solution or something. I'll have another crack at it tomorrow.

**Comment by ThePaulMcBride** [comment]
It's working now! Not my best code, but it works!

**Comment by shylands** [comment]
Great stuff, I've now styled it. Closing
