### ISSUE TITLE
Setup mailchimp embedded subscribe form

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#29]
I'd like it to include a form for the user to enter their email address and subscribe to a mailchimp list. I tried to set it up via https://www.gatsbyjs.org/packages/gatsby-plugin-mailchimp/ but got a bit lost.

So far I've installed the plugin and added the correct endpoint to gatsby-config and added a subscribe section the bottom of ChoiceGrid/items.js where the form should go.

Below is the embed code generated by mailchimp:

```
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://shylands.us12.list-manage.com/subscribe/post?u=8a0a61ac67959bc53bf568501&amp;id=eaa9d680b0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8a0a61ac67959bc53bf568501_eaa9d680b0" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by shylands** [comment]
@ThePaulMcBride @rachelfranklin1 Hey can anyone help with this one? I can handle the styling just not 100% sure how to set up with Gatsby. The work so far is in master. No rush, cheers!

**Comment by ThePaulMcBride** [comment]
This is working now! Needs some styling though. There is an option to show a message generated by mailchimp to the user when they submit the form (success, error etc). I'm just rendering this to the page now, feel free to delete it if you want.

**Comment by shylands** [comment]
Brilliant styled now. Closing cheers!
