### ISSUE TITLE
Improve image loading

### ISSUE THREAD

**Issue by ThePaulMcBride** [shylands/climatechoice#42]
Currently most images on the site have a relative path eg `../../../../my-image.svg`.

By doing it this way, we're missing out on some of the magic that Gatsby provides out of the box. It also means it is impossible for the browser to cache the images mean they flash in every time the page loads.

Instead, we should import the image at the top of the file like `import MyImage from '../../../my-image.svg'`

Then, in the image component, we can pass that variable as the source. `<img src={MyImage}/>`.

This needs done across the site but it totally worth the effort!

**Comment by ThePaulMcBride** [comment]
I've made a start on this. It works well, especially for the logo. The SVG is so small, that when Gatsby builds the site, it just includes it inline in the HTML as base64, saving a rout trip the the server.

I've also co-located the image file next to the component that is using it. Not sure if you like this or not. Have a look and let me know what you think, @shylands.

https://github.com/shylands/climatechoice/tree/master/src/components/Navbar

**Comment by shylands** [comment]
Cool! I was unaware of this. All sounds good cheers!

**Comment by shylands** [comment]
@ThePaulMcBride I'll try and update them all. I'm ok with putting an image with the component, but what do you recommend doing if the image is used in multiple places?

**Comment by ThePaulMcBride** [comment]
I'd just create in images directory folder in the components directory or something similar and import them into the components that need them the same way.
