### ISSUE TITLE
Google analytics tracking issue

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#69]
@ThePaulMcBride I've installed this https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

However from what I can see it isn't tracking anything. I haven't set this up in gatsby before so I'm not sure if I'm doing something wrong. Would you mind checking for me at somepoint to see what the craic is?

**Comment by ThePaulMcBride** [comment]
Yea, I'll check this out this evening. Can you add me to the analytics account so I can see whats going on?

**Comment by shylands** [comment]
Yep done, thanks!

**Comment by ThePaulMcBride** [comment]
Sorry, I've not had the chance to look at this tonight, I'll get it done tomorrow!

**Comment by shylands** [comment]
NP cheers!

**Comment by ThePaulMcBride** [comment]
This is sorted now. It was a problem with the sampling rate. The code copied from the plugin example was set to only track 5% of users.

**Comment by shylands** [comment]
Brilliant thanks!
