### ISSUE TITLE
Optimise pages for sharing on social media

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#7]
Each page should be optimised in a way that when it's shared on social media the viewer sees:

1. Unique page title
2. Unique page description
3. Unique share image

I know how to do this utilising [React Helmet](https://github.com/nfl/react-helmet) on each page, but it would be great if someone with a bit more technical knowledge could set up a more optimised approach to this.

**Comment by ThePaulMcBride** [comment]
I'm happy to look after this. I'll need a default image for each page and I'll provide a way for any page to overwrite it with a more specific one.

**Comment by shylands** [comment]
Awesome, wanna just use placeholders for now? I'll replace them later. Cheers!

**Comment by shylands** [comment]
@ThePaulMcBride Yo man, would you mind explaining how the SEO image override for pages works? I tried something there but don't believe I'm doing it right. 

Also, the default image is hardcoded to here, I tried adding one to the public dir but also don't think it's working.

Cheers!

**Comment by ThePaulMcBride** [comment]
Sure! The image has a default hardcoded in `gatsby-config.js` We'll need to update this when the site goes live.

For overwriting it on in any page, you just need to pass an image prop to the `<SEO/>` component that is already being rendered on each page. It has to be a full url and cannot be a relative path.

![Screenshot 2019-05-13 at 09 06 33](https://user-images.githubusercontent.com/6891650/57605540-c7bdef80-755e-11e9-919b-d3cc89112593.png)

Also, I noticed that on the `layout.js` you've included some code to update the favicon. This is all handled by a plugin which generates all of the different sizes you need. Checkout `gatsby-plugin-manifest` in `gatsby-config.js`.

**Comment by shylands** [comment]
@ThePaulMcBride Cool thanks for this. Just to confirm should I delete all of the meta I've added in layout.js or is there anything worthwhile keeping not covered?

**Comment by shylands** [comment]
Tested the image override and working well 👌

**Comment by shylands** [comment]
@ThePaulMcBride See the image implementation... I've noticed the share images usually only show a small preview when posted on social sites, compared to the larger image you usually get. You can see an example of both below. Is this something to do with the way it is setup?

![image](https://user-images.githubusercontent.com/310547/57834453-9c384080-77bc-11e9-830b-c73aec6bf4ce.png)

**Comment by ThePaulMcBride** [comment]
This is a pretty simple change.

We just need to change the twitter card type from `summary` to `summary_large_image`.
https://github.com/shylands/climatechoice/blob/master/src/components/seo.js#L47

If you want I can take a look later at making this an option that we can pass in along with the image override.

**Comment by shylands** [comment]
@ThePaulMcBride Thanks, do you think is there a benefit to having the smaller version sometimes? 

Since images tend to grab attention I'm usually in favour of showing it bigger. I've changed it to summary_large_image. Do you know if this also changes it for slack?

**Comment by ThePaulMcBride** [comment]
No, larger image is fine, as long as we have an image for each!

Slack uses the og:image header to look for the image, it doesn't really have different sizes to display, so it'll just show whatever image we provide. Facebook is the same too.

Here are the most up to date recommendations I can find. https://iamturns.com/open-graph-image-size/#cheatsheet

**Comment by ThePaulMcBride** [comment]
Is there more to do for this or can we close this issue?

**Comment by shylands** [comment]
Yep!
