### ISSUE TITLE
Decide on Yarn or npm for package management

### ISSUE THREAD

**Issue by ThePaulMcBride** [shylands/climatechoice#8]
Looks like at some point both yarn and npm have been used for installing dependencies as we have a `yarn.lock` and a `package-lock.json`.

Gatsby recommends using yarn as it's workspace feature is required when using gatsby themes. If everyone is happy with that, I can remove the `package-lock.json` and update the readme.

**Comment by shylands** [comment]
@ThePaulMcBride Yeh, I think I did that by accident. Happy to go with your recommendation

**Comment by mattbudde** [comment]
Shall we close this off ?, as it looks like @ThePaulMcBride pushed the changes ❤️

**Comment by ThePaulMcBride** [comment]
Yea, I'll close it now. I think I closed the wrong issue when trying to close this one 🤦‍♀️
