### ISSUE TITLE
Build a wee hamburger mobile nav

### ISSUE THREAD

**Issue by shylands** [shylands/climatechoice#9]
As seen in the UI mockup below, we'll need a mobile nav to support all of the main links. I'm not that picky so it doesn't have to be exactly like this if someone wants to implement it differently.

![image](https://user-images.githubusercontent.com/310547/57033020-0a70f500-6c4c-11e9-8f04-0854d03ce28b.png)

**Comment by ThePaulMcBride** [comment]
Oops...
